<a href="https://colab.research.google.com/github/Moriarty7819/Movie-recommendation-system/blob/main/Movie_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, balanced_accuracy_score

In [2]:
df=pd.read_csv('/content/dataset.csv')

In [3]:
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [4]:
df.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [6]:
df['tags']=df['genre'] + df['overview']

In [ ]:
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tags
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,"Drama,CrimeIn the continuing saga of the Corle..."

In [7]:
mov=df[['id','title','genre','overview','tags']]

In [8]:
mov.head()

,id,title,genre,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o...","Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...,"Drama,CrimeIn the continuing saga of the Corle..."

In [9]:
mov=mov.drop(columns=['genre','overview'])

In [10]:
mov.head()

,id,title,tags
0,278,The Shawshank Redemption,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,CrimeIn the continuing saga of the Corle..."

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv=CountVectorizer(max_features=10000,stop_words='english')

In [13]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [14]:
vec=cv.fit_transform(mov['tags'].values.astype('U')).toarray()

In [15]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
vec.shape

(10000, 10000)

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
sim=cosine_similarity(vec)

In [19]:
sim

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])

In [20]:
mov[mov['title']=='The Dark Knight Rises']

,id,title,tags
688,49026,The Dark Knight Rises,"Action,Crime,Drama,ThrillerFollowing the death..."

In [21]:
dist=sorted(list(enumerate(sim[1])),reverse=True,key=lambda x:x[1])
dist

[(1, np.float64(1.0)),
 (7465, np.float64(0.23186944788008412)),
 (3716, np.float64(0.2125118592516207)),
 (4068, np.float64(0.20739033894608508)),
 (4589, np.float64(0.20739033894608508)),
 (8706, np.float64(0.2032002032003048)),
 (886, np.float64(0.19925419255468718)),
 (8162, np.float64(0.19925419255468718)),
 (1155, np.float64(0.19459743752898476)),
 (8806, np.float64(0.19354838709677424)),
 (8883, np.float64(0.19050019050028574)),
 (9216, np.float64(0.1854955583040673)),
 (2069, np.float64(0.1796053020267749)),
 (3591, np.float64(0.1796053020267749)),
 (5100, np.float64(0.1796053020267749)),
 (8326, np.float64(0.1796053020267749)),
 (3710, np.float64(0.17424273674761284)),
 (8808, np.float64(0.17424273674761284)),
 (651, np.float64(0.17038855027411945)),
 (760, np.float64(0.17038855027411945)),
 (4351, np.float64(0.17038855027411945)),
 (7671, np.float64(0.17038855027411945)),
 (467, np.float64(0.16933350266692068)),
 (1120, np.float64(0.16933350266692068)),
 (1960, np.float64(0.16933350266692068)),
 (3157, np.float64(0.16933350266692068)),
 (8874, np.float64(0.16933350266692068)),
 (8877, np.float64(0.16829781403596433)),
 (892, np.float64(0.1665251238244323)),
 (2261, np.float64(0.16481712868606582)),
 (8338, np.float64(0.16481712868606582)),
 (671, np.float64(0.16245910832216473)),
 (734, np.float64(0.1624591083221647)),
 (1018, np.float64(0.1624591083221647)),
 (2483, np.float64(0.1624591083221647)),
 (8305, np.float64(0.16164477182409742)),
 (6530, np.float64(0.1606438657804998)),
 (2782, np.float64(0.16064386578049977)),
 (3206, np.float64(0.16064386578049977)),
 (5705, np.float64(0.16064386578049977)),
 (995, np.float64(0.15875015875023812)),
 (5085, np.float64(0.15875015875023812)),
 (697, np.float64(0.1567723603339241)),
 (1451, np.float64(0.1567723603339241)),
 (4743, np.float64(0.1567723603339241)),
 (6297, np.float64(0.1567723603339241)),
 (7258, np.float64(0.1567723603339241)),
 (2049, np.float64(0.15554275420956382)),
 (2169, np.float64(0.15554275420956382)),
 (4422, np.float64(0.15554275420956382)),
 (5857, np.float64(0.15554275420956382)),
 (7389, np.float64(0.15554275420956382)),
 (7847, np.float64(0.15554275420956382)),
 (8667, np.float64(0.15554275420956382)),
 (2695, np.float64(0.15401027590842437)),
 (6002, np.float64(0.15401027590842437)),
 (6387, np.float64(0.15401027590842437)),
 (1659, np.float64(0.15394740173723565)),
 (3514, np.float64(0.1531679162134967)),
 (4569, np.float64(0.1531679162134967)),
 (1310, np.float64(0.1524001524002286)),
 (8671, np.float64(0.1524001524002286)),
 (220, np.float64(0.14980117725462766)),
 (1108, np.float64(0.14980117725462766)),
 (2254, np.float64(0.14980117725462766)),
 (3812, np.float64(0.14980117725462766)),
 (5685, np.float64(0.14980117725462766)),
 (6060, np.float64(0.14980117725462766)),
 (7306, np.float64(0.14980117725462766)),
 (9672, np.float64(0.14980117725462766)),
 (1858, np.float64(0.1494406444160154)),
 (2833, np.float64(0.1494406444160154)),
 (3759, np.float64(0.1494406444160154)),
 (4716, np.float64(0.1494406444160154)),
 (5025, np.float64(0.1494406444160154)),
 (5474, np.float64(0.1494406444160154)),
 (5846, np.float64(0.1494406444160154)),
 (6191, np.float64(0.1494406444160154)),
 (7391, np.float64(0.1494406444160154)),
 (7450, np.float64(0.1494406444160154)),
 (8116, np.float64(0.1494406444160154)),
 (8299, np.float64(0.1494406444160154)),
 (9145, np.float64(0.1494406444160154)),
 (9904, np.float64(0.1494406444160154)),
 (4127, np.float64(0.14763464883937316)),
 (4481, np.float64(0.14664711502135333)),
 (5208, np.float64(0.14664711502135333)),
 (9397, np.float64(0.14664711502135333)),
 (7478, np.float64(0.14530784390894486)),
 (4344, np.float64(0.1451732372622595)),
 (57, np.float64(0.14400460822119582)),
 (876, np.float64(0.14400460822119582)),
 (1837, np.float64(0.14400460822119582)),
 (2785, np.float64(0.14400460822119582)),
 (2948, np.float64(0.14400460822119582)),
 (4745, np.float64(0.14400460822119582)),
 (5923, np.float64(0.14400460822119582)),
 (6467, np.float64(0.14400460822119582)),
 (5638, np.float64(0.1437993271357627)),
 (5723, np.float64(0.1437993271357627)),
 (3393, np.float64(0.14368424162141993)),
 (7910, np.float64(0.14368424162141993)),
 (8239, np.float64(0.1423540710868647)),
 (731, np.float64(0.1408939907352694)),
 (2901, np.float64(0.1408939907352694)),
 (3675, np.float64(0.1408939907352694)),
 (5527, np.float64(0.1408939907352694)),
 (6693, np.float64(0.1408939907352694)),
 (4392, np.float64(0.1402481783633036)),
 (85, np.float64(0.13912166872805048)),
 (335, np.float64(0.13912166872805048)),
 (381, np.float64(0.13912166872805048)),
 (887, np.float64(0.13912166872805048)),
 (2004, np.float64(0.13912166872805048)),
 (2952, np.float64(0.13912166872805048)),
 (3481, np.float64(0.13912166872805048)),
 (3518, np.float64(0.13912166872805048)),
 (4367, np.float64(0.13912166872805048)),
 (4494, np.float64(0.13912166872805048)),
 (5968, np.float64(0.13912166872805048)),
 (6563, np.float64(0.13912166872805048)),
 (9469, np.float64(0.13912166872805048)),
 (3992, np.float64(0.1382602259640567)),
 (4632, np.float64(0.1382602259640567)),
 (793, np.float64(0.13576884666042613)),
 (1810, np.float64(0.13576884666042613)),
 (1832, np.float64(0.13576884666042613)),
 (2545, np.float64(0.13576884666042613)),
 (5166, np.float64(0.13576884666042613)),
 (7622, np.float64(0.13576884666042613)),
 (1087, np.float64(0.1353825902684706)),
 (266, np.float64(0.13470397652008118)),
 (269, np.float64(0.13470397652008118)),
 (553, np.float64(0.13470397652008118)),
 (1878, np.float64(0.13470397652008118)),
 (2334, np.float64(0.13470397652008118)),
 (2502, np.float64(0.13470397652008118)),
 (2601, np.float64(0.13470397652008118)),
 (2705, np.float64(0.13470397652008118)),
 (2861, np.float64(0.13470397652008118)),
 (3196, np.float64(0.13470397652008118)),
 (3258, np.float64(0.13470397652008118)),
 (3523, np.float64(0.13470397652008118)),
 (3887, np.float64(0.13470397652008118)),
 (6132, np.float64(0.13470397652008118)),
 (8049, np.float64(0.13470397652008118)),
 (8356, np.float64(0.13470397652008118)),
 (8674, np.float64(0.13470397652008118)),
 (9252, np.float64(0.13470397652008118)),
 (9449, np.float64(0.13470397652008118)),
 (294, np.float64(0.13340746919301402)),
 (1386, np.float64(0.13340746919301402)),
 (2677, np.float64(0.13340746919301402)),
 (3390, np.float64(0.13340746919301402)),
 (5163, np.float64(0.13340746919301402)),
 (9907, np.float64(0.13340746919301402)),
 (411, np.float64(0.13116516715679058)),
 (959, np.float64(0.13116516715679058)),
 (2011, np.float64(0.13116516715679058)),
 (2457, np.float64(0.13116516715679058)),
 (4415, np.float64(0.13116516715679058)),
 (21, np.float64(0.13068205256070964)),
 (607, np.float64(0.13068205256070964)),
 (827, np.float64(0.13068205256070964)),
 (1094, np.float64(0.13068205256070964)),
 (1110, np.float64(0.13068205256070964)),
 (1512, np.float64(0.13068205256070964)),
 (2889, np.float64(0.13068205256070964)),
 (2939, np.float64(0.13068205256070964)),
 (3473, np.float64(0.13068205256070964)),
 (5586, np.float64(0.13068205256070964)),
 (7626, np.float64(0.13068205256070964)),
 (8287, np.float64(0.13068205256070964)),
 (8296, np.float64(0.13068205256070964)),
 (9308, np.float64(0.13068205256070964)),
 (270, np.float64(0.12903225806451615)),
 (1351, np.float64(0.12903225806451615)),
 (2070, np.float64(0.12903225806451615)),
 (2662, np.float64(0.12903225806451615)),
 (4139, np.float64(0.12903225806451615)),
 (4942, np.float64(0.12903225806451615)),
 (5096, np.float64(0.12903225806451615)),
 (5800, np.float64(0.12828950144769635)),
 (1220, np.float64(0.12789136689584626)),
 (4, np.float64(0.1270001270001905)),
 (105, np.float64(0.1270001270001905)),
 (282, np.float64(0.1270001270001905)),
 (392, np.float64(0.1270001270001905)),
 (447, np.float64(0.1270001270001905)),
 (448, np.float64(0.1270001270001905)),
 (673, np.float64(0.1270001270001905)),
 (762, np.float64(0.1270001270001905)),
 (929, np.float64(0.1270001270001905)),
 (1145, np.float64(0.1270001270001905)),
 (1200, np.float64(0.1270001270001905)),
 (1447, np.float64(0.1270001270001905)),
 (1770, np.float64(0.1270001270001905)),
 (2330, np.float64(0.1270001270001905)),
 (2986, np.float64(0.1270001270001905)),
 (3466, np.float64(0.1270001270001905)),
 (4030, np.float64(0.1270001270001905)),
 (4540, np.float64(0.1270001270001905)),
 (4667, np.float64(0.1270001270001905)),
 (4952, np.float64(0.1270001270001905)),
 (5110, np.float64(0.1270001270001905)),
 (6754, np.float64(0.1270001270001905)),
 (6936, np.float64(0.1270001270001905)),
 (7319, np.float64(0.1270001270001905)),
 (7712, np.float64(0.1270001270001905)),
 (7839, np.float64(0.1270001270001905)),
 (8000, np.float64(0.1270001270001905)),
 (8329, np.float64(0.1270001270001905)),
 (8583, np.float64(0.1270001270001905)),
 (8686, np.float64(0.1270001270001905)),
 (8756, np.float64(0.1270001270001905)),
 (8789, np.float64(0.1270001270001905)),
 (9703, np.float64(0.1270001270001905)),
 (9706, np.float64(0.1270001270001905)),
 (9957, np.float64(0.1270001270001905)),
 (7127, np.float64(0.12574886370696423)),
 (9229, np.float64(0.1257488637069642)),
 (2117, np.float64(0.1250610798961445)),
 (2435, np.float64(0.1250610798961445)),
 (4976, np.float64(0.1250610798961445)),
 (6949, np.float64(0.1250610798961445)),
 (7540, np.float64(0.1250610798961445)),
 (823, np.float64(0.12361284651454937)),
 (1610, np.float64(0.12361284651454937)),
 (1926, np.float64(0.12361284651454937)),
 (1933, np.float64(0.12361284651454937)),
 (2090, np.float64(0.12361284651454937)),
 (2745, np.float64(0.12361284651454937)),
 (3026, np.float64(0.12361284651454937)),
 (3405, np.float64(0.12361284651454937)),
 (4758, np.float64(0.12361284651454937)),
 (4967, np.float64(0.12361284651454937)),
 (5525, np.float64(0.12361284651454937)),
 (6960, np.float64(0.12361284651454937)),
 (7293, np.float64(0.12361284651454937)),
 (8268, np.float64(0.12361284651454937)),
 (9807, np.float64(0.12361284651454937)),
 (1871, np.float64(0.1233534278728621)),
 (747, np.float64(0.12320822072673948)),
 (1422, np.float64(0.12320822072673948)),
 (2421, np.float64(0.12320822072673948)),
 (3796, np.float64(0.12320822072673948)),
 (4201, np.float64(0.12320822072673948)),
 (4502, np.float64(0.12320822072673948)),
 (5534, np.float64(0.12320822072673948)),
 (6104, np.float64(0.12320822072673948)),
 (8263, np.float64(0.12320822072673948)),
 (9860, np.float64(0.12320822072673948)),
 (612, np.float64(0.1228075425250719)),
 (4272, np.float64(0.12220592918446108)),
 (4377, np.float64(0.12143534814378325)),
 (7032, np.float64(0.12143534814378325)),
 (92, np.float64(0.12048289933537483)),
 (1564, np.float64(0.12048289933537483)),
 (2230, np.float64(0.12048289933537483)),
 (2691, np.float64(0.12048289933537483)),
 (3844, np.float64(0.12048289933537483)),
 (4921, np.float64(0.12048289933537483)),
 (5384, np.float64(0.12048289933537483)),
 (5913, np.float64(0.12048289933537483)),
 (7926, np.float64(0.12048289933537483)),
 (8065, np.float64(0.12048289933537483)),
 (8369, np.float64(0.12048289933537483)),
 (9475, np.float64(0.12048289933537483)),
 (4867, np.float64(0.12000384018432984)),
 (5307, np.float64(0.12000384018432983)),
 (370, np.float64(0.11973686801784994)),
 (841, np.float64(0.11973686801784994)),
 (881, np.float64(0.11973686801784994)),
 (1569, np.float64(0.11973686801784994)),
 (3456, np.float64(0.11973686801784994)),
 (3512, np.float64(0.11973686801784994)),
 (4194, np.float64(0.11973686801784994)),
 (5826, np.float64(0.11973686801784994)),
 (5993, np.float64(0.11973686801784994)),
 (6261, np.float64(0.11973686801784994)),
 (6659, np.float64(0.11973686801784994)),
 (6741, np.float64(0.11973686801784994)),
 (6970, np.float64(0.11973686801784994)),
 (9336, np.float64(0.11973686801784994)),
 (2316, np.float64(0.11894651701745163)),
 (5243, np.float64(0.11894651701745163)),
 (1842, np.float64(0.11810771907149853)),
 (3345, np.float64(0.11810771907149853)),
 (5014, np.float64(0.11810771907149853)),
 (7505, np.float64(0.11810771907149853)),
 (867, np.float64(0.11791665765914455)),
 (735, np.float64(0.11757927025044308)),
 (810, np.float64(0.11757927025044308)),
 (905, np.float64(0.11757927025044308)),
 (1480, np.float64(0.11757927025044308)),
 (2160, np.float64(0.11757927025044308)),
 (2731, np.float64(0.11757927025044308)),
 (4687, np.float64(0.11757927025044308)),
 (5631, np.float64(0.11757927025044308)),
 (6087, np.float64(0.11757927025044308)),
 (6481, np.float64(0.11757927025044308)),
 (7766, np.float64(0.11757927025044308)),
 (8133, np.float64(0.11757927025044308)),
 (8242, np.float64(0.11757927025044308)),
 (8313, np.float64(0.11757927025044308)),
 (8330, np.float64(0.11757927025044308)),
 (9283, np.float64(0.11757927025044308)),
 (9775, np.float64(0.11757927025044308)),
 (3110, np.float64(0.11691309338623893)),
 (245, np.float64(0.116543309349613)),
 (3706, np.float64(0.116543309349613)),
 (9203, np.float64(0.116543309349613)),
 (4930, np.float64(0.11593472394004206)),
 (1919, np.float64(0.11503946170861017)),
 (3895, np.float64(0.11503946170861017)),
 (7606, np.float64(0.11503946170861017)),
 (9678, np.float64(0.11503946170861017)),
 (9734, np.float64(0.11498051245456849)),
 (8108, np.float64(0.11498051245456847)),
 (20, np.float64(0.11487593716012254)),
 (1903, np.float64(0.11487593716012254)),
 (1958, np.float64(0.11487593716012254)),
 (2381, np.float64(0.11487593716012254)),
 (2394, np.float64(0.11487593716012254)),
 (2509, np.float64(0.11487593716012254)),
 (3316, np.float64(0.11487593716012254)),
 (3445, np.float64(0.11487593716012254)),
 (3727, np.float64(0.11487593716012254)),
 (3749, np.float64(0.11487593716012254)),
 (4535, np.float64(0.11487593716012254)),
 (5794, np.float64(0.11487593716012254)),
 (7271, np.float64(0.11487593716012254)),
 (7805, np.float64(0.11487593716012254)),
 (8207, np.float64(0.11487593716012254)),
 (9720, np.float64(0.11487593716012254)),
 (4760, np.float64(0.11404948083653993)),
 (88, np.float64(0.11359236684941297)),
 (456, np.float64(0.11359236684941297)),
 (626, np.float64(0.11359236684941297)),
 (1288, np.float64(0.11359236684941297)),
 (1297, np.float64(0.11359236684941297)),
 (1403, np.float64(0.11359236684941297)),
 (1586, np.float64(0.11359236684941297)),
 (1873, np.float64(0.11359236684941297)),
 (2225, np.float64(0.11359236684941297)),
 (2376, np.float64(0.11359236684941297)),
 (2528, np.float64(0.11359236684941297)),
 (2807, np.float64(0.11359236684941297)),
 (3005, np.float64(0.11359236684941297)),
 (3060, np.float64(0.11359236684941297)),
 (3132, np.float64(0.11359236684941297)),
 (3159, np.float64(0.11359236684941297)),
 (3659, np.float64(0.11359236684941297)),
 (3820, np.float64(0.11359236684941297)),
 (4542, np.float64(0.11359236684941297)),
 (4744, np.float64(0.11359236684941297)),
 (4872, np.float64(0.11359236684941297)),
 (5731, np.float64(0.11359236684941297)),
 (6628, np.float64(0.11359236684941297)),
 (6696, np.float64(0.11359236684941297)),
 (6699, np.float64(0.11359236684941297)),
 (6822, np.float64(0.11359236684941297)),
 (7141, np.float64(0.11359236684941297)),
 (7287, np.float64(0.11359236684941297)),
 (7944, np.float64(0.11359236684941297)),
 (8093, np.float64(0.11359236684941297)),
 (8289, np.float64(0.11359236684941297)),
 (9009, np.float64(0.11359236684941297)),
 (9054, np.float64(0.11359236684941297)),
 (9641, np.float64(0.11359236684941297)),
 (9717, np.float64(0.11359236684941297)),
 (9950, np.float64(0.11359236684941297)),
 (5373, np.float64(0.11296650882571714)),
 (521, np.float64(0.11235088294097074)),
 (627, np.float64(0.11235088294097074)),
 (634, np.float64(0.11235088294097074)),
 (960, np.float64(0.11235088294097074)),
 (1226, np.float64(0.11235088294097074)),
 (1952, np.float64(0.11235088294097074)),
 (3494, np.float64(0.11235088294097074)),
 (3732, np.float64(0.11235088294097074)),
 (4228, np.float64(0.11235088294097074)),
 (5692, np.float64(0.11235088294097074)),
 (6852, np.float64(0.11235088294097074)),
 (7225, np.float64(0.11235088294097074)),
 (7332, np.float64(0.11235088294097074)),
 (8397, np.float64(0.11235088294097074)),
 (8721, np.float64(0.11235088294097074)),
 (9128, np.float64(0.11235088294097074)),
 (9635, np.float64(0.11235088294097074)),
 (9692, np.float64(0.11235088294097074)),
 (852, np.float64(0.11219854269064289)),
 (6528, np.float64(0.11138647983852826)),
 (1070, np.float64(0.11085479909473867)),
 (1423, np.float64(0.11085479909473867)),
 (3537, np.float64(0.11085479909473867)),
 (4516, np.float64(0.11085479909473867)),
 (6195, np.float64(0.11085479909473867)),
 (7239, np.float64(0.11085479909473867)),
 (2034, np.float64(0.109985336266015)),
 (2267, np.float64(0.109985336266015)),
 (2351, np.float64(0.109985336266015)),
 (2595, np.float64(0.109985336266015)),
 (4256, np.float64(0.109985336266015)),
 (4689, np.float64(0.109985336266015)),
 (4894, np.float64(0.109985336266015)),
 (4901, np.float64(0.109985336266015)),
 (7589, np.float64(0.109985336266015)),
 (8464, np.float64(0.109985336266015)),
 (8465, np.float64(0.109985336266015)),
 (8992, np.float64(0.109985336266015)),
 (9266, np.float64(0.109985336266015)),
 (1159, np.float64(0.10955820713295535)),
 (5448, np.float64(0.10890171046725802)),
 (12, np.float64(0.10830607221477648)),
 (190, np.float64(0.10830607221477648)),
 (322, np.float64(0.10830607221477648)),
 (334, np.float64(0.10830607221477648)),
 (353, np.float64(0.10830607221477648)),
 (759, np.float64(0.10830607221477648)),
 (888, np.float64(0.10830607221477648)),
 (964, np.float64(0.10830607221477648)),
 (991, np.float64(0.10830607221477648)),
 (1466, np.float64(0.10830607221477648)),
 (1482, np.float64(0.10830607221477648)),
 (1533, np.float64(0.10830607221477648)),
 (1988, np.float64(0.10830607221477648)),
 (2508, np.float64(0.10830607221477648)),
 (2750, np.float64(0.10830607221477648)),
 (2810, np.float64(0.10830607221477648)),
 (3362, np.float64(0.10830607221477648)),
 (3866, np.float64(0.10830607221477648)),
 (3958, np.float64(0.10830607221477648)),
 (4196, np.float64(0.10830607221477648)),
 (4567, np.float64(0.10830607221477648)),
 (4857, np.float64(0.10830607221477648)),
 (4890, np.float64(0.10830607221477648)),
 (4990, np.float64(0.10830607221477648)),
 (5093, np.float64(0.10830607221477648)),
 (5276, np.float64(0.10830607221477648)),
 (5367, np.float64(0.10830607221477648)),
 (5420, np.float64(0.10830607221477648)),
 (5939, np.float64(0.10830607221477648)),
 (5991, np.float64(0.10830607221477648)),
 (6044, np.float64(0.10830607221477648)),
 (6768, np.float64(0.10830607221477648)),
 (6823, np.float64(0.10830607221477648)),
 (7100, np.float64(0.10830607221477648)),
 (7876, np.float64(0.10830607221477648)),
 (8042, np.float64(0.10830607221477648)),
 (8050, np.float64(0.10830607221477648)),
 (8200, np.float64(0.10830607221477648)),
 (8670, np.float64(0.10830607221477648)),
 (8895, np.float64(0.10830607221477648)),
 (9250, np.float64(0.10830607221477648)),
 (9594, np.float64(0.10830607221477648)),
 (9608, np.float64(0.10830607221477648)),
 (9768, np.float64(0.10830607221477648)),
 (9811, np.float64(0.10830607221477648)),
 (1191, np.float64(0.10776318121606496)),
 (1491, np.float64(0.10776318121606496)),
 (3190, np.float64(0.10776318121606496)),
 (3870, np.float64(0.10776318121606496)),
 (4295, np.float64(0.10776318121606496)),
 (4445, np.float64(0.10776318121606496)),
 (5269, np.float64(0.10776318121606496)),
 (5297, np.float64(0.10776318121606496)),
 (5565, np.float64(0.10776318121606496)),
 (5965, np.float64(0.10776318121606496)),
 (6262, np.float64(0.10776318121606496)),
 (7266, np.float64(0.10776318121606496)),
 (7940, np.float64(0.10776318121606496)),
 (8598, np.float64(0.10776318121606496)),
 (9930, np.float64(0.10776318121606496)),
 (235, np.float64(0.1070959105203332)),
 (2471, np.float64(0.1070959105203332)),
 (3849, np.float64(0.1070959105203332)),
 (6510, np.float64(0.1070959105203332)),
 (2218, np.float64(0.10592542826647522)),
 (8963, np.float64(0.10583343916682542)),
 (119, np.float64(0.10567049305145204)),

In [22]:
for i in dist [0:5]:
  print(mov.iloc[i[0]].title)

Dilwale Dulhania Le Jayenge
The Cheetah Girls: One World
A Passage to India
Fatal Attraction
Noelle

In [23]:
def reommendation_System(movies):
  idx=mov[mov['title']==movies].index[0]
  distance=sorted(list(enumerate(sim[idx])),reverse=True,key=lambda x:x[1])
  for i in distance[0:5]:
    print(mov.iloc[i[0]].title)

In [25]:
reommendation_System("The Godfather")

The Godfather
The Godfather: Part II
Felon
House of Gucci
Gotti

In [30]:
import gradio as gr

def recommendation_System(movie):

    idx = mov[mov['title'] == movie].index[0]

    distance = sorted(
        list(enumerate(sim[idx])),
        reverse=True,
        key=lambda x: x[1]
    )

    recommendations = []

    for i in distance[1:6]:
        recommendations.append(mov.iloc[i[0]].title)

    return recommendations


def recommend(movie):

    result = recommendation_System(movie)

    return "\n".join(result)


demo = gr.Interface(
    fn=recommend,

    inputs=gr.Dropdown(
        choices=mov['title'].tolist(),
        label="🎬 Select Movie"
    ),

    outputs=gr.Textbox(
        label="🍿 Top 5 Recommendations",
        lines=6
    ),

    title="Movie Recommendation System",
    description="Select a movie and get similar recommendations using Cosine Similarity",

    theme=gr.themes.Soft()
)

demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://f1e2ce6d44877c7389.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)